---
title: "Project 1"
author: "Yuying Zhou"
date: "9/14/2020"
output: 
  rmarkdown::github_document:
      toc : true
      toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)

```

# Needed Packages
```{r packages}
#load packageds
library(httr)
library(jsonlite)
library(tidyverse)
```

# Functions to read NHL records
```{r function for records}
#create a franchise lookup table
base<- "https://records.nhl.com/site/api"
endpoint1<-"/franchise-season-records?cayenneExp=franchiseId"
call1<-paste0(base,endpoint1)
get1<-GET(call1)
get1_text<-content(get1,"text")
get1_json<-fromJSON(get1_text,flatten= TRUE)
get1_df<-as.data.frame(get1_json)
franchisetable<-select(get1_df,data.franchiseId, data.franchiseName)
flook<-franchisetable$data.franchiseId
names(flook)<-franchisetable$data.franchiseName

#create the function
records<-function(endpoint,franchise=NULL){
  base<- "https://records.nhl.com/site/api"
  if (endpoint==1){
    endpoint<-"/franchise"
    call<-paste0(base,endpoint)
    get<-GET(call)
    get_text<-content(get,"text")
    get_json<-fromJSON(get_text,flatten= TRUE)
    get_df<-as.data.frame(get_json)
  }
  else if (endpoint==2){
    endpoint<-"/franchise-team-totals"
    call<-paste0(base,endpoint)
    get<-GET(call)
    get_text<-content(get,"text")
    get_json<-fromJSON(get_text,flatten= TRUE)
    get_df<-as.data.frame(get_json)
  }
  else if (endpoint==3){
    endpoint<-"/franchise-season-records?cayenneExp=franchiseId"
   franchise<- ifelse(!is.numeric(franchise),unname(flook[franchise]),franchise)
    call<-paste0(base,endpoint,"=",franchise)
    get<-GET(call)
    get_text<-content(get,"text")
    get_json<-fromJSON(get_text,flatten= TRUE)
    get_df<-as.data.frame(get_json)
  }
  else if (endpoint==4){
    endpoint<-"/franchise-goalie-records?cayenneExp=franchiseId"
    franchise<- ifelse(!is.numeric(franchise),unname(flook[franchise]),franchise)
    call<-paste0(base,endpoint,"=",franchise)
    get<-GET(call)
    get_text<-content(get,"text")
    get_json<-fromJSON(get_text,flatten= TRUE)
    get_df<-as.data.frame(get_json)
  }
  else{
    endpoint<-"/franchise-skater-records?cayenneExp=franchiseId"
    franchise<- ifelse(!is.numeric(franchise),unname(flook[franchise]),franchise)
    call<-paste0(base,endpoint,"=",franchise)
    get<-GET(call)
    get_text<-content(get,"text")
    get_json<-fromJSON(get_text,flatten= TRUE)
    get_df<-as.data.frame(get_json)
  }
}

new<-function(franchise){
  franchise<- franchise<- ifelse(!is.numeric(franchise),unname(flook[franchise]),franchise)
  return(franchise)
}
test<-new("New Jersey Devils")
data1<-records(endpoint=1)
data2<-records(2)
data3<-records(3,"San Jose Sharks")
data4<-records(4,"San Jose Sharks")
data5<-records(5,"New Jersey Devils")

    
    
```

# Functions read stats API
```{r functions for stats}
base2<-"https://statsapi.web.nhl.com/api/v1/teams"
endpoint2<-"?expand=team.roster"
endpoint2<-"?expand=person.names"
endpoint2<-"?expand=team.schedule.next"
endpoint2<-"?expand=team.schedule.previous"
endpoint2<-"?expand=team.stats"
endpoint2<-"?expand=team.roster&season=20142015"
endpoint2<-"?teamId"
endpoint2<-"?stats=statsSingleSeasonPlayoffs "
call2<-paste0(base2,endpoint2)

#create a lookup table for team id and team name
get2<-GET(call2)
get2_text<-content(get2,"text")
get2_json<-fromJSON(get2_text,flatten= TRUE)
get2_df<-as.data.frame(get2_json)
teamtable<-select(get2_df,teams.teamName, teams.id)
tlook<-teamtable$teams.id
names(tlook)<-teamtable$teams.teamName

nhlstats<-function(modifiers){
  base2<-"https://statsapi.web.nhl.com/api/v1/teams"
  if (modifiers==1){
    modifiers<-"?expand=team.roster"
    call2<-paste0(base2,modifiers)
    get2<-GET(call2)
    get2_text<-content(get2,"text")
    get2_json<-fromJSON(get2_text,flatten= TRUE)
    get2_df<-as.data.frame(get2_json)
  }
}  
```



